# Java 异常机制

# Exception Handler:异常处理

Both Error and RuntimeException are unchecked exceptions, meaning that it indicate a flaw with the program, and usually should not be caught. for instance (NullPointerException, IndexOutOfBoundsException)

I think the main difference between the two is that RuntimeException indicate there is a error with the program, and an Error is something that is fatal but out of the program's control. (OutOfMemorryError, ThreadDeath etc.) therefore subclassing an error is bad practice because an error is usually not something that could be fixed by your program at runtime. In your program, should you need to throw something, use an exception.

## Reference

- [The Surprising Truth of Java Exceptions: What Is REALLY Going on Under the Hood?](http://blog.takipi.com/the-surprising-truth-of-java-exceptions-what-is-really-going-on-under-the-hood/)

# Failure Handler:失败处理

## Retry:失败重试

### [failsafe](https://github.com/jhalterman/failsafe#event-listeners):简单优雅地失败重试处理

1.Throwable 类是 Java 语言中所有错误或异常的超类。它的两个子类是 Error 和 Exception；

2.Error 是 Throwable 的子类，用于指示合理的应用程序不应该试图捕获的严重问题。大多数这样的错误都是异常条件。虽然 ThreadDeath 错误是一个“正规”的条件，但它也是 Error 的子类，因为大多数应用程序都不应该试图捕获它。在执行该方法期间，无需在其 throws 子句中声明可能抛出但是未能捕获的 Error 的任何子类，因为这些错误可能是再也不会发生的异常条件。Error 类体系描述了 Java 运行系统中的内部错误以及资源耗尽的情形，Error 不需要捕捉。

3.Exception 类及其子类是 Throwable 的一种形式，它指出了合理的应用程序想要捕获的条件。

4.RuntimeException 是那些可能在 Java 虚拟机正常运行期间抛出的异常的超类。可能在执行方法期间抛出但未被捕获的 RuntimeException 的任何子类都无需在 throws 子句中进行声明。它是 Exception 的子类。

_Exception：
_
1．可以是可被控制(checked) 或不可控制的(unchecked)
2．表示一个由程序员导致的错误
3．应该在应用程序级被处理

_Error：_
1．总是不可控制的(unchecked)
2．经常用来用于表示系统错误或低层资源的错误
3．如何可能的话，应该在系统级被捕捉

Java 中定义了两类异常:

1. Checked exception: 这类异常都是 Exception 的子类 。异常的向上抛出机制进行处理，假如子类可能产生 A 异常，那么在父类中也必须 throws A 异常。可能导致的问题：代码效率低，耦合度过高。

2. Unchecked exception: 这类异常都是 RuntimeException 的子类，虽然 RuntimeException 同样也是 Exception 的子类，但是它们是非凡的，它们不能通过 client code 来试图解决，所以称为 Unchecked exception 。

Checked Exception 与 Runtime Exception 的区别
Java 里有个很重要的特色是 Exception ，也就是说允许程序产生例外状况。而在学 Java 的时候，我们也只知道 Exception 的写法，却未必真能了解不同种类的 Exception 的区别。

首先，您应该知道的是 Java 提供了两种 Exception 的模式，一种是执行的时候所产生的 Exception (Runtime Exception)，另外一种则是受控制的 Exception (Checked Exception)。

所有的 Checked Exception 均从 java.lang.Exception 继承而来，而 Runtime Exception 则继承 java.lang.RuntimeException 或 java.lang.Error (实际上 java.lang.RuntimeException 的上一层也是 java.lang.Exception)。

当我们撰写程序的时候，我们很可能会对选择某种形式的 Exception 感到困扰，到底我应该选择 Runtime Exception 还是 Checked Exception ？

其实，在运作上，我们可以通过 Class 的 Method 如何产生某个 Exception 以及某个程序如何处理这个被产生来的 Exception 来了解它们之间的差异。
首先我们先建立一个 Exception

```
    public class CException extends Exception {
        public CException() {
        }

        public CException(String message) {
            super(message);
        }
    }
```

然后我们撰写一个可能产生 CException 的 Class

```
public class TestException {
	public void method1() throws CException {
		throw new CException("Test Exception");
	}

	public void method2(String msg) {
		if (msg == null) {
			throw new NullPointerException("Message is null");
		}
	}

	public void method3() throws CException {
		method1();
	}

	// 以下省略
	// ...
}
```

在这三个 method 中，我们看到了 method1 和 method2 的程序码内都会产生 Exception，但 method3 的程序码中(大括号内)，并没产生 Exception，但在 method3 的定义中，暗示了这个 method 可能产生 CException。

呼叫 method1() 的程序，必须将 method1() 包含在 try 与 catch 中，如：

```
    public class Runtest {
        // ....
        public static void main(String argv[]) {
            TestException te = new TestException();
            try {
                te.method1();
            } catch (CException ce) {
                // ....
                ce.printStackTrace();
            }
        }
        // ...
    }
```

虽然包含在 try 与 catch 中，并不表示这段程序码一定会收到 CException，但它的用意在于提醒呼叫者，执行这个 method 可能产生的意外，而使用者也必须要能针对这个意外做出相对应的处理方式。

当使用者呼叫 method2() 时，并不需要使用 try 和 catch 将程序码包起来，因为 method2 的定义中，并没有 throws 任何的 Exception ，如：

```
    public class Runtest
    {
    // ....
    public static void main(String argv[])
    {

    testException te = new testException();

    // 不会产生 Exception
    te.method2("Hello");

    // 会产生 Exception
    te.method2(null);
    }
    // ...
    }
```

程序在执行的时候，也不见得会真的产生 NullPointerException ，这种 Exception 叫做 runtime exception 也有人称为 unchecked exception ，产生 Runtime Exception 的 method (在这个范例中是 method2) 并不需要在宣告 method 的时候定义它将会产生哪一种 Exception 。

在 testException 的 method3() 中，我们看到了另外一种状况，也就是 method3 里呼叫了 method1() ，但却没有将 method1 包在 try 和 catch 之间。相反，在 method3() 的定义中，它定义了 CException，实际上就是如果 method3 收到了 CException ，它将不处理这个 CException ，而将它往外丢。当然，由于 method3 的定义中有 throws CException ，因此呼叫 method3 的程序码也需要有 try catch 才行。

因此从程序的运作机制上看，Runtime Exception 与 Checked Exception 不一样，然而从逻辑上看，Runtime Exception 与 Checked Exception 在使用的目的上也不一样。

一般而言，Checked Exception 表示这个 Exception 必须要被处理，也就是说程序设计者应该已经知道可能会收到某个 Exception(因为要 try catch 住) ，所以程序设计者应该能针对这些不同的 Checked Exception 做出不同的处理。

而 Runtime Exception 通常会暗示着程序上的错误，这种错误会导致程序设计者无法处理，而造成程序无法继续执行下去。

看看下面的例子：

String message[] = {"message1", "message2","message3"};
System.out.println(message[3]);

这段程序码在 Compile 时并没问题，但在执行时则会出现 ArrayIndexOutOfBoundException 的例外，在这种状况下，我们亦无法针对这个 Runtime Exception 做出有意义的动作，这就像是我们呼叫了 testException 中的 method2 ，却引发了它的 NullPointerException 一样，在这种状况下，我们必须对程序码进行修改，从而避免这个问题。

因此，实际上我们应该也必须要去抓取所有的 Checked Exception，同时最好能在这些 Checked Exception 发生的时候做出相对应的处理，好让程序能面对不同的状况。

然而对于 Runtime Exception ，有些人建议将它 catch 住，然后导向其它地方，让程序继续执行下去，这种作法并非不好，但它会让我们在某些测试工具下认为我们的程序码没有问题，因为我们将 Runtime Exception "处理"掉了，事实却不然！譬如很多人的习惯是在程序的进入点后用个大大的 try catch 包起来，如：

```
    public class Runtest1 {
        public static void main(String argv[]) {
            try {
                // ...
            } catch (Exception e) {
            }
        }
    }
```

在这种情况下，我们很可能会不知道发生了什么 Exception 或是从哪一行发出的，因此在面对不同的 Checked Exception 时，我们可已分别去 try catch 它。而在测试阶段时，如果碰到 Runtime Exception ，我们可以让它就这样发生，接着再去修改我们的程序码，让它避免 Runtime Exception，否则，我们就应该仔细追究每一个 Exception ，直到我们可以确定它不会有 Runtime Exception 为止！

对于 Checked Exception 与 Runtime Exception ，我想应该有不少人会有不同的观点，无论如何，程序先要能执行，这些 Exception 才有机会产生。因此，我们可以把这些 Exception 当成是 Bug ，也可以当成是不同的状况(Checked Exception)，或当成是帮助我们除错的工具(Runtime Exception)，但前提是我们需要处理这些 Exception ，如果不处理，那么问题或状况就会永远留在那里。

5.方法重写时：在子类中一个重写的方法可能只抛出父类中声明过的异常或者异常的子类

Quotes from Effective Java 2nd Edition, Item 58: Use checked exceptions for recoverable conditions and runtime exceptions for programming errors

The Java programming language provides three kinds of throwables: checked exceptions, runtime exceptions, and errors. There is some confusion among programmers as to when it is appropriate to use each kind of throwable. While the decision is not always clear-cut, there are some general rules that provide strong guidance.

The cardinal rule in deciding whether to use checked exception or an unchecked one is this:

Use checked exceptions for conditions from which the caller can reasonably be expected to recover. By throwing a checked exception, you force the caller to handle the exception in a catch clause or to propagate it outward. Each checked exception that a method is declared to throw is therefore a potent indication to the API user that associated condition is a possible outcome of invoking the method.
Use runtime exceptions to indicate programming errors. The great majority of runtime exceptions indicate precondition violations. A precondition violation is simply a failure by the client of an API to adhere to the contract specified by the API specification.
Here's an example:

When trying to read a file of arbitrary name, the file may not exists. It's not strictly a programming error when a file does not exist (e.g. perhaps it did before but was then accidentally deleted). Clients may want to recover from this. Thus, FileNotFoundException is a checked exception.
If you give a null string as a filename, then NullPointerException (or perhaps an IllegalArgumentException -- another contentious debate) should be thrown. Client of the API is supposed to provide a valid string value; null isn't. As far as the API is concerned, this is a programmer error, which was easily preventable. Both of these exceptions are runtime exceptions.
Item 59: Avoid unnecessary use of checked exceptions also provides additional guidance:

Checked exceptions are a wonderful feature of the Java programming language. Unlike return codes, they force the programmer to deal with exceptional conditions, greatly enhancing reliability. That said, overuse of checked exceptions can make an API far less pleasant to use. If a method throws one or more checked exceptions, the code that invokes the method must handle the exceptions in one or more catch blocks, or it must declare that it throws the exceptions and let them propagate outward. Either way, it places a nontrivial burden on the programmer.

The burden is justified if:

the exceptional condition cannot be prevented by proper use of the API, and
the programmer using the API can take some useful action once confronted with the exception.
Unless both of these conditions hold, an unchecked exception is more appropriate.
So here's a short summary of the recommendation from Effective Java 2nd Edition:

Preventable exceptions that happen due to API user errors should be unchecked.
Exceptions that can't be handled reasonably should also be unchecked.
Otherwise, the exception should be checked.
